name: Pay SDK Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master

    paths:
      - 'product/pay/**'
      - 'core/android/**'

permissions:
  contents: read

env:
  TEST_TIMEOUT_SECONDS: 180

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pay_integration_tests:
    name: Run Pay Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check what modules were changed
        id: what_modules_changed
        shell: bash
        run: |
          check_changes() {
            local module_path=$1
            local output_variable_name=$2

            changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- "$module_path/")

            if [ -n "$changes" ]; then
            echo "${output_variable_name}=true" >> $GITHUB_OUTPUT
            echo "${output_variable_name}=true"
            else
            echo "${output_variable_name}=false" >> $GITHUB_OUTPUT
            echo "${output_variable_name}=false"
            fi
          }

          check_changes "product/pay" "PAY_MODULE_CHANGED"
          check_changes "core/android" "CORE_MODULE_CHANGED"

      - name: Setup Required files to build SDKs
        with:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_SERVICE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
          ENCODED_STRING_DEBUG: ${{ secrets.WC_KOTLIN_DEBUG_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_DEBUG: ${{ secrets.WC_KOTLIN_DEBUG_KEYSTORE_PATH }}
          ENCODED_STRING_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE_PATH }}
          ENCODED_STRING_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE_PATH }}
        uses: ./.github/actions/ci_setup

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Pay instrumented tests
        if: ${{ steps.what_modules_changed.outputs.PAY_MODULE_CHANGED == 'true' || steps.what_modules_changed.outputs.CORE_MODULE_CHANGED == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/ci_instrumented_tests
        with:
          name: "Pay_SDK"
          command: ":product:pay:allDevicesCheck"
          projectId: ${{ secrets.WC_CLOUD_PROJECT_ID }}
          walletPrivateKey: ${{ secrets.TEST_WALLET_PRIVATE_KEY }}
          merchantApiKey: ${{ secrets.MERCHANT_API_KEY }}
          testTimeoutSeconds: ${{ github.event.inputs.testTimeoutSeconds || env.TEST_TIMEOUT_SECONDS }}
